In [1]:
import numpy as np

In [22]:
# how we can create 3D array of zeros 3x4
three_cross_four_arr=np.zeros((2,3,4))
print(f"Zeros:",three_cross_four_arr.astype(int))

Zeros: [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [21]:
# How we can create 3D array  with all value fill with 1's 
ones_arr=np.ones((3,4,3))

print(f"ones array 4x3:",ones_arr.astype(int))

ones array 4x3: [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [20]:
# Lets create 3x4 array with value 3
value_three_arr=np.full((3,3,4),3)
print(f"Array with value three::",value_three_arr)

Array with value three:: [[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]]


In [23]:
# Create a 3D array with random numbers between 1 and 9 shape 3x4.
random_arr=np.random.randint(1,10,size=(3,3,4))
print(f"Random 3D array 3x4:: ",random_arr)

Random 3D array 3x4::  [[[3 7 6 2]
  [2 5 3 1]
  [1 1 9 3]]

 [[3 8 6 8]
  [3 5 3 9]
  [1 7 9 1]]

 [[2 6 1 5]
  [1 2 5 9]
  [7 4 7 4]]]


In [24]:
print(f"length of 3D array:",len(random_arr))

length of 3D array: 3
