In [4]:
import numpy as np

In [25]:
# Numpy offers powerful shortcuts to create arrays without loops!
# If we want to create 3x3 array with all value 0
arrOfZeros= np.zeros((3,3))
print(f"Array 3 x 3 ::\n",arrOfZeros)

Array 3 x 3 ::
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# If we want  dummy array with all value 1 2x4
arrayOfOnes= np.ones((2,4))
print(f" Array 2 x 4 :\n",arrayOfOnes)

 Array 2 x 4 :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# If we want dummy array with some specific value and dimesion
fullArray=np.full((2,8),5)
print(f"Array 2 x 8 \n",fullArray)

Array 2 x 8 
 [[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [30]:
#  Indentiy Matrix
identityMatrix=np.eye(4)
print(f"Indentity Matrix \n",identityMatrix)

Indentity Matrix 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
# If we want array like range
rangeArr1=np.arange(1,10)
print("Range Array: \n", rangeArr1)
rangeArr2=np.arange(1,52,5)
print("Some interval of value: \n",rangeArr2)

Range Array: 
 [1 2 3 4 5 6 7 8 9]
Some interval of value: 
 [ 1  6 11 16 21 26 31 36 41 46 51]


In [39]:
# If we want array evenly spaced
linArr2=np.linspace(1,52,5)
print("Evenly Spaced Array: \n",linArr2)

Evenly Spaced Array: 
 [ 1.   13.75 26.5  39.25 52.  ]
