In [13]:
import numpy as np
# creating numpy array with help of python list
arr1=np.array([1,2,2,45,6])   #1D Array
arr2=np.array([[1,2,3],[4,5,6]]) #2D Array

In [15]:
print(f"Print 1D array:", arr1)
print(f"Print 2D array:", arr2)


Print 1D array: [ 1  2  2 45  6]
Print 2D array: [[1 2 3]
 [4 5 6]]


In [29]:
# Create numpy array with help range and shape
rangeArr=np.arange(20)
print("Range array:",rangeArr)
rangeArrShape= np.arange(15).reshape(3,5)
print("Range with Shape:",rangeArrShape)

Range array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Range with Shape: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Extract some information from array

# rangeArrShape.shape  # print the shape of the np array
# rangeArrShape.ndim   #print the dimension of the array(2D)
# rangeArr.ndim        #print the dimension of the array(1D)   
# rangeArr.size         #print the .size of the array
# type(arr2)              #print the type of array




numpy.ndarray