In [1]:
import numpy as np

In [ ]:
# Indexing is same as a Python List
arr=np.array([10,20,30,40])
print(arr[1]) #  aspect the output this  print is :20
print(arr[-1]) #aspecet the output this print is:40

20
40


In [13]:
# SLicing is extracting part of an array
arr1=np.array([10,20,30,40,50])
print(arr1[1:3]) # slice index from 1 to 3 output :[20,30]
print(arr1[:3]) #  slice index from 0 to 3 output:[10,20,30]
print(arr1[::2]) #slice index every 2index [10,30,50]

[20 30]
[10 20 30]
[10 30 50]


In [14]:
# Slicing return a view , not a copy. Changes affect the original array.
# If you need an independent copy of an array then use .copy()
slices=arr1[1:4].copy()
slices[0]=90
print(f"Original array:",arr1)
print(f"After slice and changes made:",slices)
    

Original array: [10 20 30 40 50]
After slice and changes made: [90 30 40]


In [15]:
# Fancy Indexig (Select Multiple Elements)
arr2=np.array([10,20,30,40,50])
inx=[0,2,4]
print(arr2[inx])   # aspected output: [10,30,50]


[10 30 50]


In [19]:
# Boolean masking(Filter Data)
mask=arr2 <= 30
print(arr2[mask])   # aspected output :[10,20,30]

[10 20 30]
