In [1]:
import numpy as np

In [9]:
# Q1: Create a 3×3 array filled with random numbers and print its shape.
randomArr=np.random.rand(3, 3)
print(f"This is a 3x3 random array:",randomArr)
print(f"This is a shape of a random array::",randomArr.shape)

This is a 3x3 random array: [[0.83021878 0.48607819 0.80542995]
 [0.99711116 0.38560042 0.17516894]
 [0.06288549 0.05034412 0.85190969]]
This is a shape of a random array:: (3, 3)


In [10]:
# Q2: Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr1=[1.1, 2.2, 3.3]
# first covert this in np array and then typeCasting like astype(int)
npArr1=np.array(arr1)
print(f"Float to integer:",npArr1.astype(int))


Float to integer: [1 2 3]


In [12]:
# Q3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr3=[1, 2, 3, 4, 5, 6]
print(f"even number from array:",arr3[::2]) # aspect output:[1,3,5]


even number from array: [1, 3, 5]


In [18]:
# Q4: Reshape a 1D array of size 9 into a 3×3 matrix.
rangeArr1=np.random.permutation(np.arange(1,10))   # permutation is generate help to generate the unique the value and arange help in ranges from to
three_cross_three_arr=rangeArr1.reshape(3,3)
print(f"First generate the random 1D array:\n",rangeArr1)
print(f"Then covert into 3x3 shape :\n",three_cross_three_arr)


First generate the random 1D array:
 [9 6 4 8 1 3 5 2 7]
Then covert into 3x3 shape :
 [[9 6 4]
 [8 1 3]
 [5 2 7]]


In [21]:
# Q5: Use boolean masking to filter numbers greater than 50 in an array.
arr4=np.arange(40,100,5)
mask=arr4>50
print(arr4[mask])

[55 60 65 70 75 80 85 90 95]
